apiVersion: v1
kind: Namespace
metadata:
  name: powerprotect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sapowerprotectadmin
  namespace: powerprotect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpowerprotectadmin
rules:
  - apiGroups: [""]
    resources: ["pvc", "pv", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["CustomResourceDefinitions"]
    verbs: ["get", "create", "update", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["bind"]
    resourceNames: ["cluster-admin"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterpowerprotectadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterpowerprotectadmin
subjects:
  - kind: ServiceAccount
    name: sapowerprotectadmin
    namespace: powerprotect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusteradminpowerprotectadmin
  namespace: powerprotect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sapowerprotectadmin
